# Generated by Django 6.0.2 on 2026-02-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnderContstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_uc', models.BooleanField(default=False)),
                ('uc_note', models.TextField(blank=True, help_text='Note for under construction mode', null=True)),
                ('uc_duration', models.DateTimeField(blank=True, help_text='End date and time of the construction', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
